option('experimental', type : 'boolean', value : false, description : 'Enable experimental features')
option('adreno_quirks', type : 'boolean', value : false, description : 'Enable adreno quirks')
option('trace', type : 'boolean', value : false, description : 'Enable TRACE statements')
option('arm_tracing', type : 'boolean', value : false, description : 'Enable ARM (both 32 and 64-bit) tracing')
option('mesa', type : 'boolean', value : false, description : 'Enable mesa headers')
option('ubuntu_camera_headers', type : 'boolean', value : false, description : 'Enable Ubuntu camera headers')
option('wayland', type : 'feature', value : 'disabled', description : 'Enable wayland support')
option('glvnd', type : 'boolean', value : false, description : 'Enable GLVND support')
option('wayland_serverside_buffers', type : 'boolean', value : true, description : 'Enable serverside buffer allocation for wayland')
option('property_cache', type : 'boolean', value : false, description : 'Enable runtime android property cache')
option('ubuntu_linker_overrides', type : 'boolean', value : false, description : 'Enable Ubuntu linker overrides')
option('arch', type : 'combo', choices : ['arm', 'arm64', 'x86', 'x86-64'], value : 'arm', description : 'Compile specific CPU target')
option('default_egl_platform', type : 'string', value : 'null', description : 'Use NAME as default EGL platform')
option('android_headers', type : 'string', value : '', description : 'Path to android headers')
option('default_hybris_ld_library_path', type : 'string', value : '', description : 'Default HYBRIS_LD_LIBRARY_PATH')
option('mali_quirks', type : 'boolean', value : false, description : 'Enable Mali GPU driver quirks')
option('stub_linker', type : 'boolean', value : false, description : 'Enable a stub linker which does nothing')
